title: Hello, world! I am Martin Smith
description: > # this means to ignore newlines until "baseurl:"
  This is my collection of Python , SQL , and all things to do with Data Science.
permalink: ':title/'
baseurl: "/martsmith187.github.io" # the subpath of your site, e.g. /blog
url: "http://martsmith187.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Martin Smith # add your name
author-img:  mart_smith.jpg # add your photo
about-author: I am a Systems Admin. Always hungry to keep learning. # add description
social-twitter: "@DataSiPythonGuy" # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: martsmith187 # add your Github handle
social-linkedin: https://www.linkedin.com/in/martin-smith-81283751 # add your Linkedin handle
social-email: mart.datasci@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
